In [129]:
"""머신러닝 개념

정의: 데이터를 기반으로 패턴을 학습하고 결과를 추론하는 알고리즘 기법.
- 지도학습(Supervised Learning), 비지도 학습(Un Supervised Learning)
    지도 학습은 분류나 회귀를 주로하며, 비지도 학습은 클러스터링과 차원 축소를 한다.

---머신러닝 용어---
데이터의 형식은 대부분 DataFrame 형태
-피처 : 데이터의 일반 속성
-레이블, 클래스, 타겟 값, 결정 값 : 정답 데이터를 의미
"""

'머신러닝 개념\n\n정의: 데이터를 기반으로 패턴을 학습하고 결과를 추론하는 알고리즘 기법.\n- 지도학습(Supervised Learning), 비지도 학습(Un Supervised Learning)\n    지도 학습은 분류나 회귀를 주로하며, 비지도 학습은 클러스터링과 차원 축소를 한다.\n\n---머신러닝 용어---\n데이터의 형식은 대부분 DataFrame 형태\n-피처 : 데이터의 일반 속성\n-레이블, 클래스, 타겟 값, 결정 값 : 정답 데이터를 의미\n'

In [130]:
import numpy as np
import pandas as pd

print('넘파이 버전 - ', np.__version__)
print('판다스 버전 - ', pd.__version__)

넘파이 버전 -  1.20.3
판다스 버전 -  1.3.4


In [131]:
import sklearn
from sklearn.datasets import load_iris

print('사이키런 버전 - ', sklearn.__version__)

사이키런 버전 -  0.24.2


In [3]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.datasets import load_iris

iris = load_iris()
print('아이리스 타입 - ',type(iris))
print('key - ', iris.keys())
# iris

print()
print('data - \n', iris.data)
print('data type - ', type(iris.data))

아이리스 타입 -  <class 'sklearn.utils.Bunch'>
key -  dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

data - 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9

In [4]:
print('target - ', iris.target)
print('target type - ', type(iris.target))
print()
print('target_names - ', iris.target_names)
print('target_names type - ', type(iris.target_names))

#여기서 setosa는 0, versicolor는 1, virginica는 2로 인코딩 해놓은게 target임.
print()
print('feature_names - ', iris.feature_names)
print('feature_names type - ', type(iris.feature_names))

target -  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
target type -  <class 'numpy.ndarray'>

target_names -  ['setosa' 'versicolor' 'virginica']
target_names type -  <class 'numpy.ndarray'>

feature_names -  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
feature_names type -  <class 'list'>


In [8]:
#feature, target을 이용해서 DF 만들기
iris_df = pd.DataFrame(data = iris.data,
                       columns=iris.feature_names)
iris_df['target'] = iris.target
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [28]:
""" 지도학습의 분류
step 01. 데이터를 분리(training data, test data).
step 02. 학습 데이터를 기반으로 ML 알고리즘 적용하여 학습 모델 생성
step 03. test 데이터를 기반으로 분류 예측을 수행
step 04. 모델에 대한 성능 평가
"""

' 지도학습의 분류\nstep 01. 데이터를 분리(training data, test data).\nstep 02. 학습 데이터를 기반으로 ML 알고리즘 적용하여 학습 모델 생성\nstep 03. test 데이터를 기반으로 분류 예측을 수행\nstep 04. 모델에 대한 성능 평가\n'

In [9]:
#데이터 분류 함수
from sklearn.model_selection import train_test_split
from sklearn.tree            import DecisionTreeClassifier
from sklearn.metrics         import accuracy_score
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [10]:
#데이터 분류
#train_test_split 함수는 리턴 값이 피처와 타켓 등 다양하기 때문에 이렇게 호출한다.
# test_size를 0.2로 두면 20%는 테스트 용으로 둔다. (셔플도 필요함)
X_train, X_test, y_train, y_test = train_test_split(iris.data,
                                                   iris.target,
                                                   test_size = 0.2,
                                                   shuffle = True,
                                                   random_state = 100)

#train_test_split(사용할 데이터, 정답, 크기, 편향도, 매번 실행 시 같은 데이터 셋 적용)

In [77]:
#학습 데이터는 120개 컬럼은 4개 -> (120, 4)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [78]:
print('train data - ', X_train)
print('train target - ', y_train)
print('test data - ', X_test)
print('test target - ', y_test)

train data -  [[5.5 2.4 3.7 1. ]
 [5.7 2.8 4.1 1.3]
 [6.  2.2 5.  1.5]
 [4.8 3.  1.4 0.1]
 [5.4 3.9 1.3 0.4]
 [6.4 3.2 4.5 1.5]
 [5.1 3.8 1.6 0.2]
 [5.5 2.5 4.  1.3]
 [6.3 3.4 5.6 2.4]
 [5.8 2.8 5.1 2.4]
 [4.5 2.3 1.3 0.3]
 [5.5 2.6 4.4 1.2]
 [7.1 3.  5.9 2.1]
 [7.2 3.6 6.1 2.5]
 [4.9 3.6 1.4 0.1]
 [4.6 3.4 1.4 0.3]
 [5.  3.  1.6 0.2]
 [5.1 3.7 1.5 0.4]
 [5.8 2.6 4.  1.2]
 [4.9 3.1 1.5 0.1]
 [5.1 3.3 1.7 0.5]
 [5.  3.2 1.2 0.2]
 [6.5 2.8 4.6 1.5]
 [7.9 3.8 6.4 2. ]
 [6.1 3.  4.9 1.8]
 [5.4 3.  4.5 1.5]
 [6.4 2.7 5.3 1.9]
 [5.7 2.9 4.2 1.3]
 [7.7 3.8 6.7 2.2]
 [6.5 3.2 5.1 2. ]
 [5.8 2.7 3.9 1.2]
 [4.6 3.6 1.  0.2]
 [6.9 3.1 5.4 2.1]
 [6.7 3.3 5.7 2.1]
 [6.3 2.8 5.1 1.5]
 [5.5 4.2 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [5.8 2.7 5.1 1.9]
 [5.4 3.9 1.7 0.4]
 [5.5 3.5 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [6.9 3.1 4.9 1.5]
 [6.5 3.  5.8 2.2]
 [6.7 3.3 5.7 2.5]
 [6.1 2.6 5.6 1.4]
 [5.4 3.7 1.5 0.2]
 [6.  3.4 4.5 1.6]
 [5.9 3.2 4.8 1.8]
 [4.6 3.1 1.5 0.2]
 [6.8 2.8 4.8 1.4]
 [4.9 2.4 3.3 1. ]
 [6.2 2.8 4.8 1.8

In [79]:
#알고리즘 모델 생성 - 학습시 fit() 사용

iris_dtc_model = DecisionTreeClassifier() #모델 생성
iris_dtc_model.fit(X_train, y_train) # 학습

DecisionTreeClassifier()

In [85]:
#분류 예측 - predict()
# predict 함수를 통해 피처를 넣으면 예측 결과를 리턴해줌
y_pred = iris_dtc_model.predict(X_test)
print('y_test (정답) -> ', y_test)
print('y_pred (예측) -> ', y_pred)

#shuffle = False면 정답이 2뿐이였지만 True로 바꾸면

y_test (정답) ->  [2 0 2 0 2 2 0 0 2 0 0 2 0 0 2 1 1 1 2 2 2 0 2 0 1 2 1 0 1 2]
y_pred (예측) ->  [2 0 2 0 2 2 0 0 2 0 0 2 0 0 2 1 1 2 2 2 2 0 2 0 1 2 1 0 1 2]


In [84]:
#예측 정확도 확인 -> shuffle가 들어가면 확률 올라감
print('acc - ', accuracy_score(y_test, y_pred))

acc -  0.9666666666666667


In [88]:
display(iris_df)
print()
print(type(iris_df))
print(type(iris_dtc_model))

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]


<class 'pandas.core.frame.DataFrame'>
<class 'sklearn.tree._classes.DecisionTreeClassifier'>


In [13]:
# 데이터 프레임 형식에서 학습 데이터와 테스트 데이터를 분리한다면?

#데이터 프레임에서 타겟만 가져오면 시리즈 형태
display(iris_df['target'])
print(type(iris_df['target']))

iris_feature = iris_df.copy()
iris_feature = iris_feature.loc[:, 'sepal length (cm)':'petal width (cm)']
#iris_feature = iris_feature.iloc[:, :-1] #교수님 답안
iris_target = iris_df.copy()
iris_target = iris_target.loc[:,['target']]
#iris_target = iris_target.iloc[:, -1]  #교수님 답안

print()
print(type(iris_feature))
print(type(iris_target))

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

<class 'pandas.core.series.Series'>

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>


In [15]:
X_train, X_test, y_train, y_test = train_test_split(iris_feature,
                                                   iris_target,
                                                   test_size = 0.2,
                                                   shuffle = True,
                                                   random_state = 100)

iris_dtc_model = DecisionTreeClassifier() #모델 생성
iris_dtc_model.fit(X_train, y_train) # 학습


y_pred = iris_dtc_model.predict(X_test)  #주의!! 여기에 학습 데이터가 들어가면 X
print('y_test (정답) -> \n', y_test)
print()
print('y_pred (예측) -> ', y_pred)

print('acc - ', accuracy_score(y_test, y_pred))

y_test (정답) -> 
      target
128       2
11        0
118       2
15        0
123       2
135       2
32        0
1         0
116       2
45        0
40        0
115       2
26        0
28        0
145       2
97        1
62        1
77        1
122       2
112       2
125       2
31        0
146       2
29        0
69        1
149       2
75        1
20        0
73        1
120       2

y_pred (예측) ->  [2 0 2 0 2 2 0 0 2 0 0 2 0 0 2 1 1 2 2 2 2 0 2 0 1 2 1 0 1 2]
acc -  0.9666666666666667


In [16]:
y_pred = iris_dtc_model.predict(X_train)  #주의!! 여기에 학습 데이터가 들어가면 X
print('y_test (정답) -> ', y_train)        #만약 들어가면 크기가 맞지 않으므로 아래도 바꿔주는데,
print('y_pred (예측) -> ', y_pred)         #정확도는 100 -> 과대적합 발생!

print('정확도 - ', accuracy_score(y_train, y_pred))

y_test (정답) ->       target
81        1
99        1
119       2
12        0
16        0
..      ...
87        1
103       2
67        1
24        0
8         0

[120 rows x 1 columns]
y_pred (예측) ->  [1 1 2 0 0 1 0 1 2 2 0 1 2 2 0 0 0 0 1 0 0 0 1 2 2 1 2 1 2 2 1 0 2 2 2 0 0
 2 0 0 0 1 2 2 2 0 1 1 0 1 1 2 0 1 1 1 1 1 1 2 2 0 1 0 1 2 2 2 1 0 0 0 0 2
 0 0 1 0 2 1 2 0 2 2 0 1 1 1 2 1 1 0 0 0 2 1 1 0 2 2 2 1 1 1 1 2 2 0 0 1 1
 1 1 2 1 1 2 1 0 0]
정확도 -  1.0


In [ ]:
"""과적합(overffiting) 문제 해결책 -> 교차 검증(cross vaildation)
-데이터의 편중을 막기 위해 사용
-KFold 방식
-교차검증은 회귀X 분류 O
"""


In [17]:
#교차 검증 방법론
#KFold, StratifiedKFold, cross_val_score, cross_validate 임포트
from sklearn.model_selection import KFold, StratifiedKFold, cross_val_score, cross_validate

In [18]:
fold_iris = load_iris()

features = fold_iris.data
label = fold_iris.target

features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [23]:
#5개의 폴더 세트를 분리하여 각 폴더 세트별 정확도를 확인해보자

cv_acc_list = []
kfold = KFold(n_splits=5) #5개 생성
#원래라면 150개 중에 30개를 테스트로 남겨두고 120개 중에서 폴더 세트를
# 다시 나누어 교차 검증을 해야함

#본 코드에서는 그냥 150개로 진행
count = 0
for train_idx, test_idx in kfold.split(features):
    count += 1
    print(count)
    print('train idx ', train_idx)
    print()
    print('test idx ', test_idx)
    
#KFold는 셔플되지 않고 교차검증이 이루어짐

1
train idx  [ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

test idx  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
2
train idx  [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 

In [43]:
cv_acc_list = []
kfold = KFold(n_splits=5)

fold_dct_model = DecisionTreeClassifier()

count = 0
for train_idx, test_idx in kfold.split(features):
    count += 1
    print(count)
    X_train, X_val = features[train_idx], features[test_idx]
    y_train, y_val = label[train_idx], label[test_idx]
#     print("X_train", X_train)
#     print("X_val", X_val)

    fold_dct_model.fit(X_train, y_train)
    fold_pred = fold_dct_model.predict(X_val)
    
    acc = accuracy_score(y_val, fold_pred)
    print('acc - ', acc)
    cv_acc_list.append(acc)
    
print('교차 검증에 대한 평균 정확도 - ', np.mean(cv_acc_list))

1
acc -  1.0
2
acc -  0.9666666666666667
3
acc -  0.8333333333333334
4
acc -  0.9333333333333333
5
acc -  0.7666666666666667
교차 검증에 대한 평균 정확도 -  0.9


In [45]:
#기존 KFold 방식 문제점

fold_iris_frm = pd.DataFrame(data=fold_iris.data,
                            columns=fold_iris.feature_names)
fold_iris_frm['target'] = fold_iris.target
fold_iris_frm

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [46]:
fold_iris_frm['target'].value_counts() #타겟의 값이 균등하다!

0    50
1    50
2    50
Name: target, dtype: int64

In [55]:
bad_fold_iris = KFold(n_splits=3)

fold_dct_model = DecisionTreeClassifier()
n_iter = 0

for train_idx, test_idx in bad_fold_iris.split(fold_iris_frm):
    n_iter += 1
    
    print(train_idx)
    print()
    print(test_idx)
    print()
    
    label_train = fold_iris_frm['target'].iloc[train_idx]
    label_val = fold_iris_frm['target'].iloc[test_idx]
    print("교차검증 횟수", n_iter)
    print()
    print("학습 레이블 데이터 분포", label_train)
    print("검증 레이블 데이터 분포", label_val)
    

#     fold_dct_model.fit(X_train, y_train)
#     fold_pred = fold_dct_model.predict(X_val)
    
#     acc = accuracy_score(y_val, fold_pred)
#     print('acc - ', acc)
#     cv_acc_list.append(acc)
    
# print('교차 검증에 대한 평균 정확도 - ', np.mean(cv_acc_list))

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103
 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121
 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139
 140 141 142 143 144 145 146 147 148 149]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]

교차검증 횟수 1

학습 레이블 데이터 분포 50     1
51     1
52     1
53     1
54     1
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 100, dtype: int32
검증 레이블 데이터 분포 0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32 

In [56]:
""" 실습1
아이리스 데이터를 이용하여 StratifiedKFold 교차 검증을 진행해보자
ramdom_state = 200
StratifiedKFold(3, 5) 평균 정확도 확인 필요"""

from sklearn.model_selection import KFold , StratifiedKFold , cross_val_score, cross_validate

fold_iris = load_iris()

features = fold_iris.data
label = fold_iris.target

cv_acc_list = []
sff = StratifiedKFold(n_splits=5)
fold_dct_model = DecisionTreeClassifier(random_state = 200)
count = 0

for train_idx, test_idx in sff.split(features, label):
    print("----------------------------------------------------------------")
    count += 1
    print("진행 횟수 - ", count)
    X_train, X_val = features[train_idx], features[test_idx]
    y_train, y_val = label[train_idx], label[test_idx]
#     print("train_idx", train_idx)
#     print("test_idx", test_idx)

    fold_dct_model.fit(X_train, y_train)
    fold_pred = fold_dct_model.predict(X_val)
    
    acc = accuracy_score(y_val, fold_pred)
    print('acc - ', acc)
    cv_acc_list.append(acc)

print("--------------------------------------------------------------------")
print('교차 검증에 대한 평균 정확도 - ', np.mean(cv_acc_list))


X_train, X_test, y_train, y_test = train_test_split(iris_feature,
                                                   iris_target,
                                                   test_size = 0.2,
                                                   shuffle = True,
                                                   random_state = 200)

iris_dtc_model = DecisionTreeClassifier() #모델 생성
iris_dtc_model.fit(X_train, y_train) # 학습


y_pred = iris_dtc_model.predict(X_test)  #주의!! 여기에 학습 데이터가 들어가면 X
print('y_test (정답) -> ', y_test)
print('y_pred (예측) -> ', y_pred)

print('acc - ', accuracy_score(y_test, y_pred))

----------------------------------------------------------------
진행 횟수 -  1
acc -  0.9666666666666667
----------------------------------------------------------------
진행 횟수 -  2
acc -  0.9666666666666667
----------------------------------------------------------------
진행 횟수 -  3
acc -  0.9
----------------------------------------------------------------
진행 횟수 -  4
acc -  1.0
----------------------------------------------------------------
진행 횟수 -  5
acc -  1.0
--------------------------------------------------------------------
교차 검증에 대한 평균 정확도 -  0.9666666666666668
y_test (정답) ->       target
84        1
122       2
28        0
24        0
75        1
109       2
81        1
98        1
80        1
100       2
124       2
2         0
34        0
44        0
128       2
13        0
93        1
41        0
63        1
137       2
19        0
60        1
126       2
11        0
47        0
18        0
96        1
107       2
141       2
53        1
y_pred (예측) ->  [1 2 0 0 1 2 1 1 1 2 2 

In [57]:
"""위 과정을 한번에 수행할 수 있는 함수가 존재! -> cross_val_score
인자로 예측모델, 피처세트, 레이블, 성능평가 지표, 폴더 수
리턴 값은 성능 값만.
"""

fold_iris = load_iris()
#데이터 분리
features = fold_iris.data
label = fold_iris.target

dt_model = DecisionTreeClassifier(random_state=100)
#인자로 예측모델, 피처세트, 레이블, 성능평가 지표, 폴더 수 / 리턴 값은 성능 값
score = cross_val_score(dt_model, features, label, scoring='accuracy', cv=5)

print(type(score))
print(score)
print("성능 값 평균 ", np.round(np.mean(score), 2))

<class 'numpy.ndarray'>
[0.96666667 0.96666667 0.9        0.93333333 1.        ]
성능 값 평균  0.95


In [62]:
#cross_validate함수를 알아보자

score = cross_validate(dt_model, features, label, scoring='accuracy', cv=5)

print(type(score))
print(score)
print("성능 값 평균 ", np.round(np.mean(score['test_score']), 2))
print()

#가지고 있는 키 값 출력
for key in score.keys():
    print(key)
    print(score[key])

<class 'dict'>
{'fit_time': array([0.00099635, 0.0009973 , 0.00099659, 0.00099802, 0.00099707]), 'score_time': array([0., 0., 0., 0., 0.]), 'test_score': array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])}
성능 값 평균  0.95

fit_time
[0.00099635 0.0009973  0.00099659 0.00099802 0.00099707]
score_time
[0. 0. 0. 0. 0.]
test_score
[0.96666667 0.96666667 0.9        0.93333333 1.        ]


In [60]:
#혼공머신 교제 243p 실습 예제 실행

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

wine = pd.read_csv('https://bit.ly/wine_csv_data')

data = wine[['alcohol', 'sugar', 'pH']].to_numpy()
target = wine['class'].to_numpy()

#훈련 세트와 테스트 세트를 나눕니다.
train_input, test_input, train_target, test_target = train_test_split(data,
                                                                     target,
                                                                     test_size=0.2,
                                                                     random_state=42)
#다시 훈련세트에서 가져와 훈련세트와 검증 세트로 나눕니다.
sub_input, val_input, sub_target, val_target = train_test_split(train_input,
                                                                 train_target,
                                                                 test_size=0.2,
                                                                 random_state=42)
# print(sub_input.shape, val_input.shape) #잘하고있는지 확인

#중간 검증 실행 - sub_input, val_input, sub_target, val_target로 모델 생성
dt = DecisionTreeClassifier(random_state=42)
dt.fit(sub_input, sub_target)
print("최종 훈련 세트 점수", dt.score(sub_input, sub_target))
print("최종 검증 세트 점수", dt.score(val_input, val_target))

#교차검증 함수 적용
from sklearn.model_selection import cross_validate
cross_score = cross_validate(dt, train_input, train_target)
import numpy as np
print("교차 검증 확률 평균", np.mean(cross_score['test_score']))

#만약 훈련 세트를 섞은 후 10-폴트 교차 검증을 수행하려면?
splitter = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
score = cross_validate(dt, train_input, train_target, cv=splitter)
print("평균 정확도 : ", np.mean(score['test_score']))

최종 훈련 세트 점수 0.9971133028626413
최종 검증 세트 점수 0.864423076923077
교차 검증 확률 평균 0.855300214703487
평균 정확도 :  0.8574181117533719


In [58]:
wine

NameError: name 'wine' is not defined