In [22]:
import numpy as np
#배열을 생성하면서 값을 초기화하는 방법
a = np.zeros(5)
print(a)
print()

b = np.zeros((2,3))
print(b)
print()

print(np.zeros((5,2), dtype='i'))
print()

print(np.zeros(5, dtype='U4'))
print()

print(np.ones((2, 3, 4), dtype='i8'))
print()

print(np.ones_like(b, dtype='f'))
print()

print(np.empty((4,3)))
print()

print(np.array([0,1,-1,0]) / np.array([1,0,0,0]))

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]

['' '' '' '' '']

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[1.26586417e-311 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 7.56587583e-307 1.86956246e-051]
 [6.23852670e+174 2.01951008e-076 6.37840272e-067]
 [1.70251336e-051 6.88765227e-042 1.20858433e+161]]

[  0.  inf -inf  nan]


C:\Users\82104\AppData\Local\Temp/ipykernel_9280/2368961079.py:26: RuntimeWarning: divide by zero encountered in true_divide
  print(np.array([0,1,-1,0]) / np.array([1,0,0,0]))
C:\Users\82104\AppData\Local\Temp/ipykernel_9280/2368961079.py:26: RuntimeWarning: invalid value encountered in true_divide
  print(np.array([0,1,-1,0]) / np.array([1,0,0,0]))


In [6]:
x2 = np.array([-1.0, -2.0])
z2 = np.array([[5.0], [10.0], [15.0]])
x2 + z2

array([[ 4.,  3.],
       [ 9.,  8.],
       [14., 13.]])

In [30]:
#넘파이 인덱싱, 슬라이싱

arr = np.arange(10) ** 2 #0부터 9까지 제곱해서 출력
print(arr)
print(arr[2])
print(arr[3:5])
arr[0:10:2] = -arr[0:10:2] #짝수만 -를 붙여서 출력
print(arr)
print()
print(arr[ : : -1]) #뒤에서 부터 출력
print()

for i in arr:
    print(i, end='\t')
print("")
print()
arr = np.arange(1, 21, 1).reshape(4,5) #4x5행렬로 바꿉니다.
print(arr)
print(arr[3,4])
print()
print(arr[0:3, 1:]) #0:3 0행부터 2행까지. 3은 포함하지 않음
print()
print(arr[1, ]) #1행 출력
print()
print(arr[-1, ])  #마지막 행 출력

[ 0  1  4  9 16 25 36 49 64 81]
4
[ 9 16]
[  0   1  -4   9 -16  25 -36  49 -64  81]

[ 81 -64  49 -36  25 -16   9  -4   1   0]

0	1	-4	9	-16	25	-36	49	-64	81	

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
20

[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]

[ 6  7  8  9 10]

[16 17 18 19 20]


In [8]:
#넘파이 일반 함수
#np.cos(), sin(), tanh(), exp()

arr = np.arange(0, 6, 1)
print(arr, np.cos(arr), np.exp(arr))

arr = np.arange(0.01, 1, 0.05)
print(np.log(arr))

[0 1 2 3 4 5] [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219] [  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]
[-4.60517019 -2.81341072 -2.20727491 -1.83258146 -1.56064775 -1.34707365
 -1.17118298 -1.02165125 -0.89159812 -0.77652879 -0.67334455 -0.5798185
 -0.49429632 -0.41551544 -0.34249031 -0.27443685 -0.21072103 -0.15082289
 -0.09431068 -0.04082199]


In [31]:
arr1 = np.array([2,3,4])
arr2 = np.array([1,5,2])
print(np.maximum(arr1, arr2)) #[2 5 4] 여기서 각 열에 대해 최대값
print(np.minimum(arr1, arr2)) #[1 3 2] 여기서 각 열에 대해 최소값
print()
print(np.sum(arr1))  #2+3+4 = 9
print(np.random.choice(100, 5)) #0~100 중에서 5개 출력
print(np.random.rand(2,3)) #2행 3열의 랜덤값 리턴
print(np.random.randn(2,3)) # 2행 3열의 랜덤 값 (표준 정규 분포)
print()

#위치를 반환하는 함수
arr = np.array([6,2,3,1,4,5])
print(np.argmax(arr), ":", arr[np.argmax(arr)])
#argmax - 최대값의 인덱스
#argmax - 최소값의 인덱스
arr3 = np.array([[0.1, 0.8, 0.2], [0.3, 0.2, 0.5], [0.9, 0.5, 0.3]])
print(arr3)
print()
print(np.argmax(arr3, axis=1)) #각 행에서 가장 큰 값의 자리
print()
print(np.argmax(arr3, axis=0)) #각 열에서 가장 큰 값의 자리

[2 5 4]
[1 3 2]

9
[21 36 87 70 88]
[[0.96366276 0.38344152 0.79172504]
 [0.52889492 0.56804456 0.92559664]]
[[ 0.44386323  0.33367433  1.49407907]
 [-0.20515826  0.3130677  -0.85409574]]

0 : 6
[[0.1 0.8 0.2]
 [0.3 0.2 0.5]
 [0.9 0.5 0.3]]

[1 2 0]

[2 0 1]


In [10]:
# 기술 통계 함수
# count(), mean(), var(), std(), median(), max(), min(), percetile()
arr = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8,
               2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])
print(len(arr)) #길이
print(np.mean(arr))  #평균
print(np.var(arr)) #분산
print(np.std(arr)) #표준 편차
print(np.max(arr), np.min(arr), np.median(arr))
print(np.percentile(arr, 25)) #1사분위의 수
print(np.percentile(arr, 50)) #2사분위의 수
print(np.percentile(arr, 100)) #4사분위의 수 -> 최대 값

26
4.8076923076923075
115.23224852071006
10.734628476137871
23 -24 5.0
0.0
5.0
23.0


In [20]:
#난수 발생 카운팅
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [46]:
#데이터 순서를 바꾸는 방법
arr = np.arange(10)
print(arr)
np.random.shuffle(arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[6 4 3 1 5 9 2 8 0 7]


In [37]:
#샘플링
arr = np.array([6, 2, 3, 1, 4, 5])
print("arr : ", arr)
print(np.random.choice(arr, 5, replace=False)) #5개 선택
print(np.random.choice(10, 3, replace=False))  #10개 중에 3개만 선택
print(np.random.choice(5, 10))  #5개 중에 10개 선택 -> 중복 허용
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])  #p는 확률 부여

arr :  [6 2 3 1 4 5]
[4 1 5 3 2]
[2 3 5]
[2 3 2 4 3 3 0 3 0 4]


array([3, 3, 2, 3, 2, 3, 2, 3, 3, 3])

In [71]:
#randint() 정수 난수 발생
#np.random.seed(0) #시드 박으면 값 고정됨
print(np.random.randint(5, size=10)) #10포함 안함
print()
print(np.random.randint(10, 20, size=20))
print()
print(np.random.randint(10, 20, size=(3,5))) #3행 5열의 array 반환

[1 0 4 3 3 4 2 3 1 3]

[13 12 17 13 19 19 15 19 18 13 18 15 19 10 17 10 11 16 16 14]

[[15 17 16 10 11]
 [16 16 14 12 12]
 [14 14 13 11 10]]


In [80]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
              12, 13, 14, 15, 16, 17, 18, 19, 20])
#배열에서 3의 배수를 찾아라
list_3 = []
for i in x:
    if i%3 == 0:
        list_3.append(i)
print(list_3)
print()
# 배열에서 4로 나누면 1이 남는 수를 찾아라
list_4 = []
for i in x:
    if i%4 == 1:
        list_4.append(i)
print(list_4)
print()
# 배열에서 3으로 나누면 나누어지고, 4로 나누면 1이 남는 수를 찾아라
list_5 = []
for i in x:
    if (i%3 == 0) & (i%4 == 1):
        list_5.append(i)
print(list_5)
print()

print("-----------한 줄 표현--------")
x [x%3==0]
x [x%4==1]
x [(x%3==0) & (x%4==1)]

[3, 6, 9, 12, 15, 18]

[1, 5, 9, 13, 17]

[9]

-----------한 줄 표현--------


array([ 3,  6,  9, 12, 15, 18])